# Your Wi-Fi SSID and password
wifi_ssid: "<WIFI-SSID>"
wifi_password: "<WIFI-PASS>"

# Ota password to prevent unwanted changes
ota_password: "<OTA-PASS>"

# All fallback hotspot wifi pass
fallback_hs_password: "<FALL-BACK-WIFI-PASS>"